; #######################################################################################
; # This Inno Setup script was generated by unSigned's Setup Projects Converter         # 
; # Copyright (c) 2016 - 2019 Slappy & unSigned, s. r. o. All Rights Reserved.          # 
; # Visit http://www.unsigned.sk/ for more details.                                     # 
; ####################################################################################### 
 
; This script was created from .vdproj file. Not all features from .vdproj file may have been transfered.
 
; See the Inno Setup documentation at http://www.jrsoftware.org/ for details on creating script files! 
 
;--------------------------------

; Product details
#define PRODUCT_NAME "VideoSplitter"
#define PRODUCT_CODE "{{4CE2C92E-589F-4679-868E-0836C559A538}"
#define PRODUCT_VERSION "1.3.0"
#define MANUFACTURER "DevCraft"
#define TITLE "VideoSplitter"

[Setup]
AppName={#PRODUCT_NAME}
AppVersion={#PRODUCT_VERSION}
AppId={#PRODUCT_CODE}
DefaultDirName={pf}\{#MANUFACTURER}\{#PRODUCT_NAME}
DefaultGroupName={#PRODUCT_NAME}
AppCopyright=Copyright (c) 2020 {#MANUFACTURER}
AppPublisher={#MANUFACTURER}
OutputDir=Release
OutputBaseFilename=SetupWizard

[Files]
Source: "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Security.SecureString\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Security.SecureString.dll"; DestDir: "{app}\"; StrongAssemblyName: "System.Security.SecureString, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL, ProcessorArchitecture=MSIL"; Flags: "gacinstall sharedfile uninsnosharedfileprompt"
Source: "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Runtime.InteropServices.RuntimeInformation\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.RuntimeInformation.dll"; DestDir: "{app}\"; StrongAssemblyName: "System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL, ProcessorArchitecture=MSIL"; Flags: "gacinstall sharedfile uninsnosharedfileprompt"
Source: "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Runtime.Serialization.Xml\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Serialization.Xml.dll"; DestDir: "{app}\"; StrongAssemblyName: "System.Runtime.Serialization.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL, ProcessorArchitecture=MSIL"; Flags: "gacinstall sharedfile uninsnosharedfileprompt"
Source: "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Globalization.Extensions\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Globalization.Extensions.dll"; DestDir: "{app}\"; StrongAssemblyName: "System.Globalization.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL, ProcessorArchitecture=MSIL"; Flags: "gacinstall sharedfile uninsnosharedfileprompt"
Source: "..\..\ffmpegSplitter\icon.ico"; DestDir: "{app}\"; DestName: "icon.ico"; Flags: "ignoreversion"
Source: "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Xml.XPath.XDocument\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Xml.XPath.XDocument.dll"; DestDir: "{app}\"; StrongAssemblyName: "System.Xml.XPath.XDocument, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL, ProcessorArchitecture=MSIL"; Flags: "gacinstall sharedfile uninsnosharedfileprompt"
Source: "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Runtime.Serialization.Primitives\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Serialization.Primitives.dll"; DestDir: "{app}\"; Flags: "ignoreversion"
Source: "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Diagnostics.StackTrace\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Diagnostics.StackTrace.dll"; DestDir: "{app}\"; StrongAssemblyName: "System.Diagnostics.StackTrace, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL, ProcessorArchitecture=MSIL"; Flags: "gacinstall sharedfile uninsnosharedfileprompt"
Source: "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Diagnostics.Tracing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Diagnostics.Tracing.dll"; DestDir: "{app}\"; StrongAssemblyName: "System.Diagnostics.Tracing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL, ProcessorArchitecture=MSIL"; Flags: "gacinstall sharedfile uninsnosharedfileprompt"
Source: "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Runtime.Serialization.Xml\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Serialization.Xml.dll"; DestDir: "{app}\"; Flags: "ignoreversion"
Source: "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Security.Cryptography.Algorithms\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Security.Cryptography.Algorithms.dll"; DestDir: "{app}\"; StrongAssemblyName: "System.Security.Cryptography.Algorithms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL, ProcessorArchitecture=MSIL"; Flags: "gacinstall sharedfile uninsnosharedfileprompt"
Source: "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Diagnostics.Tracing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Diagnostics.Tracing.dll"; DestDir: "{app}\"; Flags: "ignoreversion"
Source: "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Net.Sockets\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Sockets.dll"; DestDir: "{app}\"; StrongAssemblyName: "System.Net.Sockets, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL, ProcessorArchitecture=MSIL"; Flags: "gacinstall sharedfile uninsnosharedfileprompt"
Source: "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.IO.Compression.dll"; DestDir: "{app}\"; Flags: "ignoreversion"
Source: "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ValueTuple\v4.0_4.0.0.0__cc7b13ffcd2ddd51\System.ValueTuple.dll"; DestDir: "{app}\"; StrongAssemblyName: "System.ValueTuple, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL, ProcessorArchitecture=MSIL"; Flags: "gacinstall sharedfile uninsnosharedfileprompt"
Source: "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Threading.Overlapped\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Threading.Overlapped.dll"; DestDir: "{app}\"; StrongAssemblyName: "System.Threading.Overlapped, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL, ProcessorArchitecture=MSIL"; Flags: "gacinstall sharedfile uninsnosharedfileprompt"
Source: "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Data.Common\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Data.Common.dll"; DestDir: "{app}\"; StrongAssemblyName: "System.Data.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL, ProcessorArchitecture=MSIL"; Flags: "gacinstall sharedfile uninsnosharedfileprompt"
Source: "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.IO.Compression.FileSystem.dll"; DestDir: "{app}\"; Flags: "ignoreversion"
Source: "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Runtime.Serialization.Primitives\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Serialization.Primitives.dll"; DestDir: "{app}\"; StrongAssemblyName: "System.Runtime.Serialization.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL, ProcessorArchitecture=MSIL"; Flags: "gacinstall sharedfile uninsnosharedfileprompt"
Source: "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll"; DestDir: "{app}\"; StrongAssemblyName: "netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL, ProcessorArchitecture=MSIL"; Flags: "gacinstall sharedfile uninsnosharedfileprompt"
Source: "..\..\packages\NReco.VideoInfo.LT.1.1.0\lib\net20\NReco.VideoInfo.LT.dll"; DestDir: "{app}\"; Flags: "ignoreversion"
Source: "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Net.Http.dll"; DestDir: "{app}\"; Flags: "ignoreversion"
Source: "..\..\ffmpegSplitter\obj\Debug\ffmpegSplitter.exe"; DestDir: "{app}\"; DestName: "ffmpegSplitter.exe";

[Registry]
Root: HKLM; Subkey: "Software\{#MANUFACTURER}"; Flags: uninsdeletekeyifempty
Root: HKCU; Subkey: "Software\{#MANUFACTURER}"; Flags: uninsdeletekeyifempty

[Icons]
Name: "{userprograms}\DevCraft\VideoSplitter"; Filename: "{app}\ffmpegSplitter.exe"; WorkingDir: "{app}\"; IconFilename: "{app}\icon.ico"; IconIndex: "0"; Flags: createonlyiffileexists
Name: "{userdesktop}\VideoSplitter"; Filename: "{app}\ffmpegSplitter.exe"; WorkingDir: "{app}\"; IconFilename: "{app}\icon.ico"; IconIndex: "0"; Flags: createonlyiffileexists
